# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    # valid drivers options include "gd" or "gmagick" or "imagick"
    filter_sets:
        cache: ~
        thumbs:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
